### ISSUE TITLE
ZEB release timeline?

### ISSUE THREAD

**Issue by Parskatt** [xuelunshen/gim#11]
Hi, great work!

I'm wondering if you have a timeline for the release your proposed benchmark.
Personally I think this is more important than releasing the training code.

I've personally had some issues even downloading the related training sets (e.g. GL3D seems to be down now?).

Maybe authors of those datasets could allow you to bundle only the data used for the benchmark into an easy download (perhaps with some LICENSE restrictions)?

**Comment by xuelunshen** [comment]
Hello, Johan, 

I really like your DKM and RoMa. Their high performance is impressive.

I am eager to release all the code related to gim, including ZEB, as soon as possible.
However, I have been busy with matters related to my doctoral graduation recently, including my thesis and oral defense. 

Therefore, as soon as I have some free time, I will continue to push forward with the open source work of gim.

I am glad you are interested in ZEB. Please wait a little longer. I really appreciate your interest and support.

**Comment by xuelunshen** [comment]
Hello, @Parskatt 

Sorry for keeping you waiting. I just released the test data and scripts for `ZEB`. If you encounter any issues during use, please let me know, and I will resolve them as soon as possible. Thank you for your patience. 🤗
