### ISSUE TITLE
Please provide more detailed install instruction.

### ISSUE THREAD

**Issue by nicolasFL82** [xuelunshen/gim#14]
I can not install on ubuntu 18.04

please update the information.

1. the python version.
2. requirement file.

Thank you!

**Comment by xuelunshen** [comment]
To ensure compatibility with RoMa in the future, I recommend creating an environment using `conda create -n gim python=3.9`. You can install the environment by directly copying and pasting the commands provided below into the terminal. I previously tried providing a requirement file, but I received feedback that there might be a possibility of installation failure with it. Therefore, I suggest directly pasting the commands, which will also allow for environment installation.

```bash
conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge
pip install albumentations==1.0.1 --no-binary=imgaug,albumentations
pip install pytorch-lightning==1.5.10
pip install opencv-python==4.5.3.56
pip install imagesize==1.2.0
pip install kornia==0.6.10
pip install einops==0.3.0
pip install loguru==0.5.3
pip install joblib==1.0.1
pip install yacs==0.1.8
pip install h5py==3.1.0
```
