### ISSUE TITLE
非常感谢您的开源工作！我本地测试结果的召回率比hugface上online结果差，请问是否有什么参数可调试呢？

### ISSUE THREAD

**Issue by wintercat1994** [xuelunshen/gim#17]

**Comment by wintercat1994** [comment]
同样两张图在hugface和本地的测试效果：

![_import_61569b8de183d2 95002561_frame_1__import_61569b8de183d2 95002561_frame_30_gim_dkm_match](https://github.com/user-attachments/assets/f6afe5f3-b0b4-498a-b4de-85026a08b46e)
![Uploading 截屏2024-07-25 15.03.47.png…]()

**Comment by xuelunshen** [comment]
你好, 我这边只看到一张图, 是不是另一张图上传失败了.

huggingface 的结果和这个仓库的结果不一样是因为 huggingface 的代码对图像进行了等比的缩放和padding.
这个在另一个 issue 也有一些讨论, 你也可以去那里看下.

https://github.com/xuelunshen/gim/issues/12

**Comment by wintercat1994** [comment]
<img width="1331" alt="截屏2024-07-25 15 03 47" src="https://github.com/user-attachments/assets/911e28ee-cc53-47d0-96d0-9dba697019f3">
谢谢 这里是另一张图

**Comment by xuelunshen** [comment]
@wintercat1994 我后面有空的话会把 GitHub 的效果对齐到 huggingface 的版本, 不过你得等我一下.

**Comment by wintercat1994** [comment]
> @wintercat1994 我后面有空的话会把 github 的效果对齐到 huggingface 的版本, 不过你得等我一下.

好的好的，辛苦您了，多谢～

**Comment by xuelunshen** [comment]
@wintercat1994 
我现在更新了这里都的代码, 使其和 huggingface 的在线模型的表现一致了. 你可以去尝试一下, 如果遇到任何问题可以在这里继续提问.
I have now updated the code here to make it consistent with the performance of Huggingface's online model. You can give it a try, and if you encounter any problems, you can continue to ask questions here.

**Comment by songkemail** [comment]
@xuelunshen 作者，您好，感谢这么棒的开源项目，可否一起合作，我的微信是songkewetchat

**Comment by xuelunshen** [comment]
@songkemail 我们要不先邮件沟通?

**Comment by songkemail** [comment]
xuelun@stu.xmu.edu.cn，请问这是您邮箱地址？

**Comment by xuelunshen** [comment]
@songkemail 是的 🤝
