### ISSUE TITLE
Batch training mode of dkm

### ISSUE THREAD

**Issue by Graysonggg** [xuelunshen/gim#20]
Thank you for your excellent work! 
I am wondering why the batch size of dkm can only be 1?
I have tried other batchsizes, but the dimensions of bs will be flattened in the sample phase.
I would appreciate your reply.

**Comment by xuelunshen** [comment]
Hello, @Graysonggg, Thank you for your recognition and attention. Since the official code for DKM only allows a batch size of 1, we have not made any changes to it. If you would like to have a larger batch size, we can discuss here how to modify the code.
