### ISSUE TITLE
Missing weight file

### ISSUE THREAD

**Issue by lnexenl** [xuelunshen/gim#24]
I am trying to run reconstruction scripts, and I found that decoder_epoch_20.pth is missing from the repo, and original website for this weight(http://sceneparsing.csail.mit.edu/model/pytorch) has been down for several years. Could you please upload this weight?

**Comment by xuelunshen** [comment]
I just tested the [Google Drive](https://drive.google.com/file/d/1YswCj58VuVhqEpMKQ_k0QJb3_mMdpF8M/view?usp=sharing) and [OneDrive](https://stuxmueducn-my.sharepoint.com/:u:/g/personal/xuelun_stu_xmu_edu_cn/EUR_XMay5b5FtWelmqXiLi4Bcnv4G1w5b2aYjhqS-Ds_ow) download links in the [3D reconstruction](https://github.com/xuelunshen/gim?tab=readme-ov-file#-3d-reconstruction). Looks like they are both accessible. Could you try it again?

**Comment by lnexenl** [comment]
OK, I don't know what happens but it seems to be right now 🤣
