### ISSUE TITLE
RuntimeError: CUDA out of memory during 3D reconstruction.

### ISSUE THREAD

**Issue by sean880304** [xuelunshen/gim#25]
Hi, first of all thank you for the amazing work. I've tried the 3d reconstruction but encountered "CUDA out of memory" problem. I get this error while it's about to perform dense matching. 

`RuntimeError: CUDA out of memory. Tried to allocate 5.17 GiB (GPU 0; 9.76 GiB total capacity; 2.49 GiB already allocated; 4.22 GiB free; 3.50 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.`

I though it could be batch size is too large, later i found out that batch_size is already set to 1 in match_dense.py. I've also tried playing around parameters like max_kps, dfactor, cell_size, resize_max, etc. but none worked. Perhaps you could shed some light on how to reduce the cuda memory needed? Much appreciated!

**Comment by xuelunshen** [comment]
Could you tell me which line of code raise this error ?

**Comment by sean880304** [comment]
i managed to reduce to memory needed by setting `upsample_preds=False` and changing `height=480, width=640` in hloc/matchers/dkm.py. but the error remains. Full traceback is as following:

`$ sh reconstruction.sh test`
![Screenshot from 2024-09-20 16-04-25](https://github.com/user-attachments/assets/7100f201-b987-4ef7-9554-5814a0c3ca66)

Thank you for your time.

**Comment by xuelunshen** [comment]
https://github.com/xuelunshen/gim/blob/e06dba6c939ea5f4be8a11071df771d1956d3fcb/hloc/matchers/dkm.py#L98
Try to change 8192 to 4096, this will reduce the number of matches participating in reconstruction and may lead to worse reconstruction results
