### ISSUE TITLE
gim_lightglue是否支持其它特征提取方法？

### ISSUE THREAD

**Issue by zkkgit** [xuelunshen/gim#30]
作者你好，我看demo.py代码，gim_lightglue模型使用的是superpoint提取的特征，请问是否也支持其它提取特征的方法？例如aliked

**Comment by xuelunshen** [comment]
https://github.com/xuelunshen/gim/blob/e06dba6c939ea5f4be8a11071df771d1956d3fcb/networks/lightglue/superpoint.py#L344-L347

如果你是想替代 SuperPoint 返回值中的 keypoints, 那是没问题的, 你在返回这个 pred 的时候, keypoints 用 aliked 的, 然后用 aliked 的关键点坐标去 SuperPoint 的 dense_desc 采样 descriptors, 然后输入到 lightglue 就行.

---

If you want to replace the keypoints in the SuperPoint return value, that's not a problem. When returning this pred, use the keypoints from ALIKED, then use ALIKED's keypoint coordinates to sample descriptors from SuperPoint's dense_desc, and then input them into LightGlue.
