### ISSUE TITLE
High Video Memory Usage When Running the Code

### ISSUE THREAD

**Issue by SirJackYang** [xuelunshen/gim#31]
Hello,

I've encountered an issue with high video memory (VRAM) usage when executing the code provided in this repository

Here are the details of my environment and the steps I took:

Operating System: Windows 10
GPU Model: NVIDIA GeForce RTX 4080 with 16G memory
CUDA Version: CUDA 11.8 with pytorch==2.3.0
Image resoluction: 1800*2000

![image](https://github.com/user-attachments/assets/95ad17f6-a2a5-43e3-ac41-9faf3c9e96fe)

I tried to resize the image using the following code, but the video memory usage is still very high.
![image](https://github.com/user-attachments/assets/cdde334f-6767-481c-a5f0-b177949082ca)
![image](https://github.com/user-attachments/assets/f086f44a-5624-4c12-b6c5-63a5e7e770d9)

![image](https://github.com/user-attachments/assets/3bc2af2b-bc15-43f8-9d38-ab906130df4e)

**Comment by xuelunshen** [comment]
如果你想尝试 `demo.py` 里面的 `gim_dkm`, 你需要改变下面这行代码的数值, `(672, 896)` 代表图像输入以后会被缩放到这个大小, 你可以对这个图像尺寸进行等比缩小, 比如 `(480, 640)`.

If you want to try `gim_dkm` at `demo.py`, you need to change the value of the code below. `(672, 896)` means that the image will be zoomed to this size later. You can reduce the image's size by an equal proportion, such as `(480, 640)`.

https://github.com/xuelunshen/gim/blob/e06dba6c939ea5f4be8a11071df771d1956d3fcb/demo.py#L409

**Comment by SirJackYang** [comment]
好的，明白了，感谢
