### ISSUE TITLE
Weights license

### ISSUE THREAD

**Issue by mingless** [xuelunshen/gim#35]
Hey, congrats and thanks for the great work. Could you please clarify what is the current licensing situation? As I understand it the source code is provided under the MIT license? Under what license are the weights for gim_dkm and gim_lightglue? Are these restricted because of the data used for training?

**Comment by xuelunshen** [comment]
Thank you for your recognition. The licenses for $GIM_{DKM}$ and $GIM_{LightGlue}$ are also MIT, as our disclaimer states, the weights and code can only be used for research. These restricted are due to the training data.
