### ISSUE TITLE
release loftr model ?

### ISSUE THREAD

**Issue by sunshineywz123** [xuelunshen/gim#6]
congraduation, thanks for your work. could you please release the loftr model?

**Comment by ttaohe** [comment]
when will release gim+LoFTR model weight?

**Comment by xuelunshen** [comment]
@sunshineywz123 @ttaohe 

We will release it, so please be patient for a little while longer and thank you for your ATTENTION.

**Comment by xuelunshen** [comment]
@sunshineywz123 @ttaohe

Thank you for your patience. We have just released the network weights and code for `gim_loftr`.
