### ISSUE TITLE
Is there room for optimizing the inference speed and GPU memory consumption of the model?

### ISSUE THREAD

**Issue by NickJony** [xuelunshen/gim#7]
congraduation, thanks for your work. Great job！
I would like to inquire about the possibility of optimizing the inference speed and GPU memory usage of the model. Based on my testing, inference on two images takes approximately 3.5 seconds on a 3090, with a maximum memory usage of 17GB.

**Comment by xuelunshen** [comment]
Thank you for your attention. We're working on what you're talking about, and we're looking forward to improving the speed of inference as much as we can while keeping the performance of GIM_DKM the same.

**Comment by xuelunshen** [comment]
Thank you for your attention. We're working on it.

**Comment by Vincentqyw** [comment]
+1. BTW, is there any progress now?

**Comment by Vincentqyw** [comment]
> Thank you for your attention. We're working on it.

+1. BTW, is there any progress now?

**Comment by xuelunshen** [comment]
> > Thank you for your attention. We're working on it.
> 
> +1. BTW, is there any progress now?

Currently, we are conducting various experiments and explorations. Please be patient and wait for a little while. Thank you for your interest and attention.

**Comment by jrdimale** [comment]
Hi! is there any progress now regarding this issue?

**Comment by nastenkaneitzsche** [comment]
> > > Thank you for your attention. We're working on it.
> > 
> > 
> > +1. BTW, is there any progress now?
> 
> Currently, we are conducting various experiments and explorations. Please be patient and wait for a little while. Thank you for your interest and attention.
Hi, is there any update?
