### ISSUE TITLE
GIM implement in hloc?

### ISSUE THREAD

**Issue by yaoyao-jpg** [xuelunshen/gim#9]
Thank you all for the amazing work! 
As you said in #3 : “The code for SfM is based on [hloc](https://github.com/cvg/Hierarchical-Localization). In detail, we have imitated the LoFTR in hloc to implement the SfM for DKM” . To implement GIM, [hloc](https://github.com/cvg/Hierarchical-Localization) need to add a new interface in [hloc/extractors/](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/extractors) or [hloc/matchers/](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/matchers), could you release the code for that?

**Comment by puhuajiang** [comment]
Yeah, same question!

**Comment by xuelunshen** [comment]
@yaoyao-jpg @puhuajiang Thank you for your attention and interest of gim. I will submit a PR later to [hloc](https://github.com/cvg/Hierarchical-Localization). Please be patient and wait a little longer.

**Comment by xuelunshen** [comment]
@yaoyao-jpg @puhuajiang Thank you for your patience. We have just released the code for 3D reconstruction. Thank you for your waiting and attention.
